import Ciencia from "./assets/ciencia.png";
import Esportes from "./assets/esportes.png";
import Filosofia from "./assets/filosofia.png";
import Geografia from "./assets/geografia.png";
import Historia from "./assets/historia.png";
import Literatura from "./assets/literatura.png";
import Tecnologia from "./assets/tecnologia.png";

export const imgs = [
  Ciencia,
  Esportes,
  Filosofia,
  Geografia,
  Historia,
  Literatura,
  Tecnologia,
];

export const categories = {
  historia: "Historia",
  literatura: "Literatura",
  esportes: "Esportes",
  ciencia: "Ciencia",
  filosofia: "Filosofia",
  tecnologia: "Tecnologia",
  geografia: "Geografia",
};

const {
  historia,
  tecnologia,
  literatura,
  esportes,
  ciencia,
  filosofia,
  geografia,
} = categories;

export const questions = [
  {
    id: 1,
    difficulty: "Fácil",
    question: "Que evento deu início à Primeira Guerra Mundial?",
    category: historia,
    correct_answer:
      "O assassinato do arquiduque Francisco Ferdinando da Áustria",
    incorrect_answers: [
      "O naufrágio do Titanic",
      "Invasão da Polónia pela Alemanha",
      "A revolução Francesa",
    ],
  },
  {
    id: 2,
    difficulty: "Fácil",
    question: 'Quem é o autor de "Cem Anos de Solidão"? ',
    category: literatura,
    correct_answer: "Gabriel García Márquez",
    incorrect_answers: ["Julio Cortázar", "Mario Vargas Llosa", "Pablo Neruda"],
  },
  {
    id: 3,
    difficulty: "Fácil",
    question: "Em que esporte um disco é usado?",
    category: esportes,
    correct_answer: "Hóquei no gelo",
    incorrect_answers: ["Futebol", "Basquete", "Beisebol"],
  },
  {
    id: 4,
    difficulty: "Medio",
    question: "Que substância é conhecida como 'molécula da vida'?",
    category: ciencia,
    correct_answer: "DNA",
    incorrect_answers: ["Glicose", "Insulina", "Proteína"],
  },
  {
    id: 5,
    difficulty: "Difícil",
    question: "Quem é considerado o pai da filosofia ocidental?",
    category: filosofia,
    correct_answer: "Sócrates",
    incorrect_answers: ["Aristóteles", "Platão", "Nietzsche"],
  },
  {
    id: 6,
    difficulty: "Medio",
    question: "Em que ano foi fundada a empresa Apple?",
    category: tecnologia,
    correct_answer: "1976",
    incorrect_answers: ["1984", "1991", "1967"],
  },
  {
    id: 7,
    difficulty: "Fácil",
    question: "Qual é o maior rio do mundo?",
    category: geografia,
    correct_answer: "O Rio Amazonas",
    incorrect_answers: ["O Rio Nilo", "O Rio Yangtze", "O Rio Mississipi"],
  },
  {
    id: 8,
    difficulty: "Medio",
    question: "Qual é o maior oceano do mundo?",
    category: geografia,
    correct_answer: "O Oceano Pacífico",
    incorrect_answers: [
      "O Oceano Atlântico",
      "O Oceano Indiano",
      "O Oceano Ártico",
    ],
  },
  {
    id: 9,
    difficulty: "Difícil",
    question: "Qual é a obra mais famosa de William Shakespeare?",
    category: literatura,
    correct_answer: "Hamlet",
    incorrect_answers: ["Romeu e Julieta", "Macbeth", "Rei Lear"],
  },
  {
    id: 10,
    difficulty: "Medio",
    question: "O que é medido pela escala Richter?",
    category: ciencia,
    correct_answer: "A magnitude dos terremotos",
    incorrect_answers: [
      "A velocidade do som",
      "A intensidade dos furacões",
      "A temperatura em graus Fahrenheit",
    ],
  },
  {
    id: 11,
    difficulty: "Fácil",
    question: "Qual país ganhou a primeira Copa do Mundo de Futebol?",
    category: esportes,
    correct_answer: "Uruguai",
    incorrect_answers: ["Brasil", "Argentina", "Alemanha"],
  },
  {
    id: 12,
    difficulty: "Médio",
    question: "O que é o efeito estufa?",
    category: ciencia,
    correct_answer: "Um fenômeno atmosférico que retém o calor na Terra",
    incorrect_answers: [
      "Um tipo de casa de vidro para plantas",
      "Um processo químico para conservar alimentos",
      "Um tipo de sistema de aquecimento para edifícios",
    ],
  },
  {
    id: 13,
    difficulty: "Médio",
    question:
      "Em que ano foram realizados os primeiros Jogos Olímpicos modernos?",
    category: esportes,
    correct_answer: "1896",
    incorrect_answers: ["1900", "1924", "1936"],
  },
  {
    id: 14,
    difficulty: "Fácil",
    question: "Qual é o maior planeta do sistema solar?",
    category: ciencia,
    correct_answer: "Júpiter",
    incorrect_answers: ["Saturno", "Netuno", "Urano"],
  },
  {
    id: 15,
    difficulty: "Fácil",
    question: "Quem escreveu a obra 'Memórias Póstumas de Brás Cubas'?",
    category: literatura,
    correct_answer: "Machado de Assis",
    incorrect_answers: [
      "Clarice Lispector",
      "Gabriel García Márquez",
      "Fernando Sabino",
    ],
  },
  {
    id: 16,
    difficulty: "Médio",
    question: "Qual é o elemento químico mais abundante na Terra?",
    category: ciencia,
    correct_answer: "Oxigênio",
    incorrect_answers: ["Nitrogênio", "Ferro", "Silício"],
  },
  {
    id: 17,
    difficulty: "Médio",
    question: "Qual é o país mais populoso do mundo?",
    category: geografia,
    correct_answer: "China",
    incorrect_answers: ["Índia", "Estados Unidos", "Brasil"],
  },
  {
    id: 18,
    difficulty: "Médio",
    question: "Quem é considerado o pai da filosofia ocidental?",
    category: filosofia,
    correct_answer: "Sócrates",
    incorrect_answers: ["Platão", "Aristóteles", "Descartes"],
  },
  {
    id: 19,
    difficulty: "Difícil",
    question: "Que cientista propôs a teoria do Big Bang?",
    category: ciencia,
    correct_answer: "Georges Lemaître",
    incorrect_answers: ["Albert Einstein", "Stephen Hawking", "Isaac Newton"],
  },
  {
    id: 20,
    difficulty: "Fácil",
    question: 'Quem é o autor do romance "O velho e o mar"?',
    category: literatura,
    correct_answer: "Ernest Hemingway",
    incorrect_answers: [
      "William Shakespeare",
      "J.K. Rowling",
      "F. Scott Fitzgerald",
    ],
  },
  {
    id: 21,
    difficulty: "Fácil",
    question: "Qual é o maior órgão do corpo humano?",
    category: ciencia,
    correct_answer: "A pele",
    incorrect_answers: ["O fígado", "O coração", "Os pulmões"],
  },
  {
    id: 22,
    difficulty: "Médio",
    question: "Quem é o criador do sistema operacional Linux?",
    category: tecnologia,
    correct_answer: "Linus Torvalds",
    incorrect_answers: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg"],
  },
  {
    id: 23,
    difficulty: "Médio",
    question: "Em que ano terminou a Segunda Guerra Mundial?",
    category: historia,
    correct_answer: "1945",
    incorrect_answers: ["1939", "1941", "1943"],
  },
  {
    id: 24,
    difficulty: "Fácil",
    question: "Qual é o planeta mais próximo do Sol?",
    category: ciencia,
    correct_answer: "Mercúrio",
    incorrect_answers: ["Vênus", "Marte", "Júpiter"],
  },
  {
    id: 25,
    difficulty: "Médio",
    question: "Que escritor é conhecido por ter escrito 'Cem anos de solidão'?",
    category: literatura,
    correct_answer: "Gabriel García Márquez",
    incorrect_answers: ["Jorge Luis Borges", "Pablo Neruda", "Julio Cortázar"],
  },
  {
    id: 26,
    difficulty: "Difícil",
    question: "Que país é o maior em termos de superfície terrestre?",
    category: geografia,
    correct_answer: "Rússia",
    incorrect_answers: ["Estados Unidos", "China", "Austrália"],
  },
  {
    id: 27,
    difficulty: "Médio",
    question: "Qual é a capital do Canadá?",
    category: geografia,
    correct_answer: "Ottawa",
    incorrect_answers: ["Toronto", "Montreal", "Vancouver"],
  },
  {
    id: 28,
    difficulty: "Fácil",
    question: "Que elemento químico tem o símbolo H?",
    category: ciencia,
    correct_answer: "Hidrogênio",
    incorrect_answers: ["Hélio", "Ferro", "Concreto"],
  },
  {
    id: 29,
    difficulty: "Médio",
    question: "Que jogador de futebol ganhou mais Bolas de Ouro na história?",
    category: esportes,
    correct_answer: "Lionel Messi",
    incorrect_answers: ["Cristiano Ronaldo", "Johan Cruyff", "Diego Maradona"],
  },
  {
    id: 30,
    difficulty: "Fácil",
    question: "Em que ano ocorreu a Revolução Francesa?",
    category: historia,
    correct_answer: "1789",
    incorrect_answers: ["1848", "1917", "1492"],
  },

  {
    id: 31,
    difficulty: "Fácil",
    category: tecnologia,
    question: "O que significa a sigla HTML?",
    correct_answer: "HyperText Markup Language",
    incorrect_answers: [
      "Hyperlinks and Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinking Text Markup Language",
    ],
  },
  {
    id: 32,
    difficulty: "Fácil",
    category: tecnologia,
    question: "Qual é o navegador web mais utilizado no mundo?",
    correct_answer: "Google Chrome",
    incorrect_answers: ["Safari", "Firefox", "Internet Explorer"],
  },
  {
    id: 33,
    difficulty: "Fácil",
    category: tecnologia,
    question:
      "Que linguagem de programação é mais utilizada para o desenvolvimento web?",
    correct_answer: "JavaScript",
    incorrect_answers: ["Python", "Java", "C++"],
  },
  {
    id: 34,
    difficulty: "Médio",
    category: tecnologia,
    question: "O que é um servidor web?",
    correct_answer: "Um programa que recebe e processa solicitações HTTP",
    incorrect_answers: [
      "Um programa que envia e-mails",
      "Um programa que protege a privacidade dos usuários online",
      "Um programa que realiza operações matemáticas complexas",
    ],
  },
  {
    id: 35,
    difficulty: "Médio",
    category: tecnologia,
    question: "O que é um ataque de phishing?",
    correct_answer:
      "Uma tentativa de obter informações confidenciais através de um e-mail falso",
    incorrect_answers: [
      "Um vírus que danifica os arquivos do computador",
      "Um tipo de ataque DDoS",
      "Uma tentativa de sequestrar o tráfego de internet",
    ],
  },
  {
    id: 36,
    difficulty: "Médio",
    category: tecnologia,
    question: "O que é um arquivo CSV?",
    correct_answer: "Um arquivo de texto com valores separados por vírgulas",
    incorrect_answers: [
      "Um arquivo de áudio comprimido",
      "Um arquivo de imagem em formato vetorial",
      "Um arquivo de vídeo de alta definição",
    ],
  },
  {
    id: 37,
    difficulty: "Difícil",
    category: tecnologia,
    question: "O que é um algoritmo de criptografia assimétrica?",
    correct_answer: "Um método de criptografia que usa duas chaves diferentes",
    incorrect_answers: [
      "Um método de criptografia que usa a mesma chave para criptografar e descriptografar",
      "Um método de criptografia que não usa chaves",
      "Um método de criptografia usado apenas em aplicações militares",
    ],
  },
  {
    id: 38,
    difficulty: "Difícil",
    category: tecnologia,
    question: "O que é uma rede privada virtual (VPN)?",
    correct_answer: "Uma conexão segura a uma rede privada através da internet",
    incorrect_answers: [
      "Uma rede de computadores em uma organização",
      "Uma rede de computadores conectados à internet",
      "Uma rede de computadores que só utiliza tecnologia sem fio",
    ],
  },
  {
    id: 39,
    difficulty: "Difícil",
    category: historia,
    question: "Em que ano ocorreu a Guerra dos Cem Anos?",
    correct_answer: "1337",
    incorrect_answers: ["1066", "1415", "1642"],
  },
  {
    id: 40,
    difficulty: "Fácil",
    category: historia,
    question: "Em que ano ocorreu o ataque a Pearl Harbor?",
    correct_answer: "1941",
    incorrect_answers: ["1939", "1942", "1945"],
  },
  {
    id: 41,
    difficulty: "Médio",
    category: historia,
    question: "Que tratado deu fim à Primeira Guerra Mundial?",
    correct_answer: "Tratado de Versalhes",
    incorrect_answers: [
      "Tratado de Tordesilhas",
      "Tratado de Westfália",
      "Tratado de Nanquim",
    ],
  },
  {
    id: 42,
    difficulty: "Difícil",
    category: historia,
    question: "Quem foi o último imperador da Dinastia Qing na China?",
    correct_answer: "Puyi",
    incorrect_answers: ["Hongwu", "Wuzong", "Kangxi"],
  },
  {
    id: 43,
    difficulty: "Fácil",
    category: historia,
    question: "Qual foi o nome da primeira expedição de Cristóvão Colombo?",
    correct_answer: "A Santa Maria",
    incorrect_answers: ["A Pinta", "A Nina", "A Santíssima Trindade"],
  },

  {
    id: 44,
    difficulty: "Médio",
    question:
      "Qual foi o primeiro país a enviar um objeto feito pelo homem à lua?",
    category: historia,
    correct_answer: "Estados Unidos",
    incorrect_answers: ["União Soviética", "China", "Japão"],
  },
  {
    id: 45,
    difficulty: "Difícil",
    question:
      "Qual foi a primeira cidade no mundo a ter uma população de mais de um milhão de habitantes?",
    category: historia,
    correct_answer: "Roma",
    incorrect_answers: ["Atenas", "Babilônia", "Nínive"],
  },
  {
    id: 46,
    difficulty: "Fácil",
    question: "Quem foi o primeiro presidente dos Estados Unidos?",
    category: historia,
    correct_answer: "George Washington",
    incorrect_answers: [
      "Thomas Jefferson",
      "Abraham Lincoln",
      "Franklin D. Roosevelt",
    ],
  },
  {
    id: 47,
    difficulty: "Médio",
    question: "Qual foi a primeira dinastia a governar na China?",
    category: historia,
    correct_answer: "Xia",
    incorrect_answers: ["Han", "Tang", "Song"],
  },
  {
    id: 48,
    difficulty: "Fácil",
    question: 'Quem escreveu a obra "Dom Quixote de la Mancha"?',
    category: literatura,
    correct_answer: "Miguel de Cervantes",
    incorrect_answers: [
      "Gabriel García Márquez",
      "Jorge Luis Borges",
      "Pablo Neruda",
    ],
  },
  {
    id: 49,
    difficulty: "Médio",
    question:
      "Qual das seguintes novelas é escrita por Gabriel García Márquez?",
    category: literatura,
    correct_answer: "Cem anos de solidão",
    incorrect_answers: [
      "Rayuela",
      "A cidade e os cães",
      "A casa dos espíritos",
    ],
  },
  {
    id: 50,
    difficulty: "Difícil",
    question: 'Quem escreveu "A metamorfose"?',
    category: literatura,
    correct_answer: "Franz Kafka",
    incorrect_answers: ["Virginia Woolf", "James Joyce", "F. Scott Fitzgerald"],
  },
  {
    id: 51,
    difficulty: "Fácil",
    question: 'Quem escreveu "O retrato de Dorian Gray"?',
    category: literatura,
    correct_answer: "Oscar Wilde",
    incorrect_answers: ["Edgar Allan Poe", "Emily Bronte", "Charles Dickens"],
  },
  {
    id: 52,
    difficulty: "Médio",
    question:
      "Qual das seguintes obras não foi escrita por William Shakespeare?",
    category: literatura,
    correct_answer: "Moby Dick",
    incorrect_answers: ["Hamlet", "Macbeth", "Otelo"],
  },
  {
    id: 53,
    difficulty: "Difícil",
    question:
      "Qual das seguintes obras de José Saramago recebeu o Prêmio Nobel de Literatura?",
    category: literatura,
    correct_answer: "Ensaio sobre a cegueira",
    incorrect_answers: [
      "A caverna",
      "O evangelho segundo Jesus Cristo",
      "As intermitências da morte",
    ],
  },

  {
    id: 54,
    difficulty: "Fácil",
    question: 'Quem escreveu o romance "O apanhador no campo de centeio"?',
    category: literatura,
    correct_answer: "J.D. Salinger",
    incorrect_answers: [
      "F. Scott Fitzgerald",
      "Ernest Hemingway",
      "Tennessee Williams",
    ],
  },
  {
    id: 55,
    difficulty: "Difícil",
    question: "Qual é o maior país da África?",
    category: geografia,
    correct_answer: "Argélia",
    incorrect_answers: ["Sudão", "Líbia", "República Democrática do Congo"],
  },
  {
    id: 56,
    difficulty: "Fácil",
    question: "Qual é o maior país do mundo?",
    category: geografia,
    correct_answer: "Rússia",
    incorrect_answers: ["China", "Estados Unidos", "Canadá"],
  },
  {
    id: 57,
    difficulty: "Médio",
    question: "Em que continente se encontra o lago Baikal?",
    category: geografia,
    correct_answer: "Ásia",
    incorrect_answers: ["Europa", "África", "América do Sul"],
  },
  {
    id: 58,
    difficulty: "Médio",
    question: "Qual é o país mais populoso do mundo?",
    category: geografia,
    correct_answer: "China",
    incorrect_answers: ["Índia", "Estados Unidos", "Indonésia"],
  },
  {
    id: 59,
    difficulty: "Difícil",
    question: "Qual é a montanha mais alta do mundo?",
    category: geografia,
    correct_answer: "O Monte Everest",
    incorrect_answers: ["O K2", "O Mont Blanc", "O Aconcágua"],
  },
  {
    id: 60,
    difficulty: "Difícil",
    question: "Qual é o país mais pequeno do mundo?",
    category: geografia,
    correct_answer: "O Vaticano",
    incorrect_answers: ["Mônaco", "Nauru", "Tuvalu"],
  },
  {
    id: 61,
    difficulty: "Médio",
    question: "Qual é o país mais extenso da África?",
    category: geografia,
    correct_answer: "Argélia",
    incorrect_answers: ["Nigéria", "Egito", "África do Sul"],
  },
  {
    id: 62,
    difficulty: "Fácil",
    question: "Que país ganhou a Copa do Mundo da FIFA em 2018?",
    category: esportes,
    correct_answer: "França",
    incorrect_answers: ["Alemanha", "Brasil", "Argentina"],
  },
  {
    id: 63,
    difficulty: "Fácil",
    question: "Que esporte se joga em Wimbledon?",
    category: esportes,
    correct_answer: "Tênis",
    incorrect_answers: ["Golfe", "Futebol", "Rugby"],
  },
  {
    id: 64,
    difficulty: "Médio",
    question: "Quantos pontos vale um touchdown no futebol americano?",
    category: esportes,
    correct_answer: "6",
    incorrect_answers: ["4", "7", "5"],
  },
  {
    id: 65,
    difficulty: "Médio",
    question:
      "Qual é o jogador de basquete com mais anéis de campeonato na NBA?",
    category: esportes,
    correct_answer: "Bill Russell",
    incorrect_answers: [
      "Michael Jordan",
      "Kareem Abdul-Jabbar",
      "LeBron James",
    ],
  },

  {
    id: 66,
    difficulty: "Médio",
    question: "Qual é o país de origem do futebolista Lionel Messi?",
    category: esportes,
    correct_answer: "Argentina",
    incorrect_answers: ["Brasil", "Espanha", "Portugal"],
  },
  {
    id: 67,
    difficulty: "Difícil",
    question: "Em que ano se celebraram os Jogos Olímpicos de Pequim?",
    category: esportes,
    correct_answer: "2008",
    incorrect_answers: ["2012", "2004", "2016"],
  },
  {
    id: 68,
    difficulty: "Difícil",
    question: "Quem é o máximo goleador na história da Liga Espanhola?",
    category: esportes,
    correct_answer: "Lionel Messi",
    incorrect_answers: ["Cristiano Ronaldo", "Telmo Zarra", "Hugo Sánchez"],
  },
  {
    id: 69,
    difficulty: "Difícil",
    question: 'Em que esporte se utiliza o termo "smash"?',
    category: esportes,
    correct_answer: "Badminton",
    incorrect_answers: ["Voleibol", "Tênis", "Squash"],
  },
  {
    id: 70,
    category: filosofia,
    difficulty: "Fácil",
    question: "Qual é a obra mais conhecida de Platão?",
    correct_answer: "A República",
    incorrect_answers: ["O Banquete", "Timeu", "Fedão"],
  },
  {
    id: 71,
    category: filosofia,
    difficulty: "Médio",
    question: "Qual é o conceito central da filosofia de Descartes?",
    correct_answer: "O cogito ergo sum",
    incorrect_answers: ["O empirismo", "O materialismo", "A fenomenologia"],
  },
  {
    id: 72,
    category: filosofia,
    difficulty: "Difícil",
    question: "O que é a dialética na filosofia de Hegel?",
    correct_answer: "O método para chegar à verdade mediante a contradição",
    incorrect_answers: [
      "A criação de um sistema filosófico",
      "A negação da realidade",
      "A análise dos processos cognitivos",
    ],
  },
  {
    id: 73,
    category: filosofia,
    difficulty: "Médio",
    question: "O que é o niilismo na filosofia?",
    correct_answer: "A negação de todos os valores e crenças",
    incorrect_answers: [
      "A afirmação da existência de um ser superior",
      "A crença na reencarnação",
      "A negação da existência do mundo externo",
    ],
  },
  {
    id: 74,
    category: filosofia,
    difficulty: "Difícil",
    question: "O que é a desconstrução na filosofia de Jacques Derrida?",
    correct_answer:
      "A análise crítica da relação entre os significados e os conceitos",
    incorrect_answers: [
      "A criação de novos conceitos a partir da combinação dos antigos",
      "A busca da verdade absoluta",
      "A negação da existência da linguagem",
    ],
  },
  {
    id: 75,
    category: filosofia,
    difficulty: "Fácil",
    question: "O que é a ética?",
    correct_answer: "O ramo da filosofia que estuda a moral e a conduta humana",
    incorrect_answers: [
      "O ramo da filosofia que estuda a lógica",
      "O ramo da filosofia que estuda a mente",
      "O ramo da filosofia que estuda o conhecimento",
    ],
  },
  {
    id: 76,
    category: filosofia,
    difficulty: "Médio",
    question: "O que é o imperativo categórico na filosofia de Kant?",
    correct_answer: "A regra moral que se deve seguir em qualquer situação",
    incorrect_answers: [
      "A crença na existência de um Deus criador",
      "A negação da liberdade humana",
      "A afirmação da existência de uma verdade absoluta",
    ],
  },
  {
    id: 77,
    difficulty: "Fácil",
    question: 'Quem foi o autor da obra "A República"?',
    category: filosofia,
    correct_answer: "Platão",
    incorrect_answers: ["Aristóteles", "Sócrates", "Nietzsche"],
  },
  {
    id: 78,
    difficulty: "Médio",
    question:
      "Qual é o termo filosófico para se referir ao estudo do conhecimento?",
    category: filosofia,
    correct_answer: "Epistemologia",
    incorrect_answers: ["Ontologia", "Metafísica", "Lógica"],
  },

  {
    id: 79,
    difficulty: "Difícil",
    question: 'Quem escreveu o livro "O mundo como vontade e representação"?',
    category: filosofia,
    correct_answer: "Arthur Schopenhauer",
    incorrect_answers: [
      "Friedrich Nietzsche",
      "Immanuel Kant",
      "Jean-Paul Sartre",
    ],
  },
  {
    id: 80,
    difficulty: "Difícil",
    question: "Qual é a partícula subatômica mais pesada?",
    category: ciencia,
    correct_answer: "Quark top",
    incorrect_answers: ["Elétron", "Próton", "Nêutron"],
  },
  {
    id: 81,
    category: ciencia,
    difficulty: "Médio",
    question: "O que é a camada de ozônio?",
    correct_answer:
      "Uma camada de gás que protege a Terra da radiação ultravioleta do sol",
    incorrect_answers: [
      "Uma camada de nuvens na atmosfera",
      "A camada mais externa da Terra",
      "Uma camada de gases que produz o efeito estufa",
    ],
  },
  {
    id: 82,
    category: ciencia,
    difficulty: "Difícil",
    question: "O que é a antimatéria?",
    correct_answer:
      "Uma forma de matéria que tem propriedades opostas à matéria ordinária",
    incorrect_answers: [
      "Uma forma de matéria que não tem carga elétrica",
      "Uma forma de matéria que não tem massa",
      "Uma forma de energia que tem a capacidade de desintegrar a matéria",
    ],
  },
  {
    id: 83,
    difficulty: "Fácil",
    question: 'O que é a sigla "CPU" em inglês?',
    category: tecnologia,
    correct_answer: "Central Processing Unit",
    incorrect_answers: [
      "Computer Personal Unit",
      "Central Personal Unit",
      "Computer Processing Unit",
    ],
  },
  {
    id: 84,
    difficulty: "Médio",
    question: "Qual é o nome do primeiro computador eletrônico digital?",
    category: tecnologia,
    correct_answer: "ENIAC",
    incorrect_answers: ["UNIVAC", "COLOSSUS", "EDSAC"],
  },
];
